### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by janbiedermann** [boazsegev/iodine#76] opened 2019-06-27 10:57 UTC
When using iodine for running specs, specs are treated as failed, even though they are successful, because iodine crashes on exit.
See end of log here: https://travis-ci.org/isomorfeus/isomorfeus-react/builds/551249475

Does not happen with other rack servers.

**Comment by boazsegev** [comment] 2019-06-27 11:54
(TL;DR): a simple solution would be to exit iodine using [the `Iodine.stop` method](https://www.rubydoc.info/github/boazsegev/iodine/master/Iodine%2Estop) in the main process, instead of sending a signal. Since iodine will respect RSpec's signal handler and forward it the signal, using signals might not be the behavior you desire or expect.

---

The issue you. describe **might** not be an iodine issue, but rather an issue with the testing suite.

According to [this line](https://travis-ci.org/isomorfeus/isomorfeus-react/builds/551249475#L370), the server receives an exit signal in cluster more:

> INFO: Server is running 2 workers X 1 thread with facil.io 0.7.0.beta9 (epoll)
> ...
> INFO: Server Detected exit signal.

The rest of the log indicates that the shutdown process is left incomplete. There's no error message as to why the root / master process might be terminated prematurely.

**This leads me to suspect it has to do with the testing suite somehow catching the `SIGINT` / `SIGTERM` signal somewhere and terminating the main iodine process pre-maturely**.

Note that, *unlike some servers*, **iodine supports signal forwarding**. This means that if a signal handler is set, iodine will (also) forward the signal to the signal handler.

For example, notice what happens when signaling iodine in `irb`. Since `irb` sets it's own signal handler and since that handler raises an exception, a superfluous error is reported by `irb` (unlike when running iodine in stand alone mode, without setting additional signal handlers):

```ruby
require 'iodine'
Iodine.threads = 1
Iodine.run_after(1000) { Process.kill("INT", Process.pid) }
Iodine.start
```

The `RSpec` log report indicates that it received the `SIGINT` signal, [as indicated here](https://travis-ci.org/isomorfeus/isomorfeus-react/builds/551249475#L384):

> RSpec is shutting down and will print the summary report... Interrupt **again** to force quit.

This leads me to believe that the RSpec framework set a signal handler and that it received the signal.

Assuming this is the issue, **a simple solution would be to exit iodine using [the `Iodine.stop` method](https://www.rubydoc.info/github/boazsegev/iodine/master/Iodine%2Estop) in the main process** (rather then sending a signal).

**Note**:

This might also be related to an issue with the Opal framework used by the testing suite.

I noticed that [Opal monkey patches the Signal class to remove the `trap` function](https://github.com/opal/opal/blob/3c8d93ea8b3ed12b4c49c51cc96d092570c9f64c/opal/corelib/process.rb). While other servers might not set signal handlers because of the monkey patch, iodine will ignore the monkey patched version and set up actual signal handlers. Though I doubt this should result in the crash, it could explain why the issue is unnoticed when using other servers.

There are other issues with the tests and I might not have noticed all of them.

For example, the testing suite assumes that `Iodine::Rack.run` returns a thread ([it calls `join` on that thread](https://github.com/isomorfeus/isomorfeus-puppetmaster/blob/536ded9b290bf0e9932e5f0e11772236477f98fe/ruby/lib/isomorfeus/puppetmaster/server_registration.rb#L38)). However, this is not the case. `Iodine::Rack.run` returns `true` unless an exception was raised.

**Comment by janbiedermann** [comment] 2019-06-27 13:01
Thank you for the detailed explanation!

**Comment by janbiedermann** [comment] 2019-06-27 14:03
Following your advice i added:
```
RSpec.configure do |config|
  config.after(:suite) do
    STDERR.puts "Calling Iodine.stop"
    Iodine.stop
  end
end
```
I also fixed the .join issue and found another exception during stop and fixed it. The result however is the same, see https://travis-ci.org/isomorfeus/isomorfeus-react/builds/551327566

Locally on macOS i get:
```
[ lots of dots ]
..Calling Iodine.stop


Finished in 1 minute 28.32 seconds (files took 12.64 seconds to load)
199 examples, 0 failures

INFO: Server Detected exit signal.
INFO: (54053) detected exit signal.
INFO: (54054) detected exit signal.
INFO: (54055) detected exit signal.
INFO: (54056) detected exit signal.

RSpec is shutting down and will print the summary report... Interrupt again to force quit.
rake aborted!
Interrupt: 
/Users/jan/workspace/isomorfeus-react/Rakefile:11:in `system'
/Users/jan/workspace/isomorfeus-react/Rakefile:11:in `block in <top (required)>'
/Users/jan/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/jan/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => default => ruby_specs
(See full trace by running task with --trace)
core:ruby jan$ INFO: (54055) cleanup complete.
INFO: (54056) cleanup complete.
INFO: (54054) cleanup complete.
INFO: (54053) cleanup complete.
INFO:    ---  Shutdown Complete  ---



core:ruby jan$ echo $?
1
```

**Comment by janbiedermann** [comment] 2019-06-27 14:12
Looks like Iodine.stop doesn't do anything:
```
RSpec.configure do |config|
  config.after(:suite) do
    STDERR.puts "Calling Iodine.stop"
    Iodine.stop
    STDERR.puts "Called Iodine.stop"
  end
end
```
Leads to:
```
[ lots of dots ]..Calling Iodine.stop
Called Iodine.stop


Finished in 1 minute 25.99 seconds (files took 12.15 seconds to load)
199 examples, 0 failures

INFO: Server Detected exit signal.
INFO: (54445) detected exit signal.
INFO: (54446) detected exit signal.
INFO: (54447) detected exit signal.
INFO: (54448) detected exit signal.
[ etc. ]
```

**Comment by janbiedermann** [comment] 2019-06-27 14:51
Using:
```
RSpec.configure do |config|
  config.after(:suite) do
    STDERR.puts "Calling Iodine.stop"
    STDERR.puts "Master: #{Iodine.master?}"
    STDERR.puts "Worker: #{Iodine.worker?}"
    Iodine.stop
    STDERR.puts "Called Iodine.stop"
  end
end
```
Leads to:
```
[ lots of dots ]..Calling Iodine.stop
Master: true
Worker: true
Called Iodine.stop
[same as before]
core:ruby jan$ echo $?
1
```
Is Iodine.master is the process Iodine.stop should be called from, the main process?

**Comment by boazsegev** [comment] 2019-06-27 22:34
Hi @janbiedermann and thank you for your patience.

I reviewed the shutdown signal logic and it seems that using `Iodine.stop` in cluster mode will automatically send a `SIGINT` signal in order to make sure all the workers shut down.

This means that cluster mode can't be used in RSpec right now. This is compatibility issue I will try to fix.

As a temporary workaround, use iodine with a single process and call `Iodine.stop` (no signal should be raised).

As for your questions:

> **Looks like Iodine.stop doesn't do anything**

Hmmm... I'm not sure why it isn't working for you. Observe this example (run in `irb`):

```ruby
require 'iodine'
Iodine.threads = 1
Thread.new { sleep(0.5); Iodine.stop } # Or: Iodine.run_after(500) { Iodine.stop }
Iodine.start
```

Running this code shows that `Iodine.stop` stops the server.

> **Is Iodine.master is the process Iodine.stop should be called from, the main process?**

Iodine's main process is the one `Iodine.stop` should be called from... *However*, the `master` process identification is only valid when called from within an iodine process.

For example:

```ruby
require 'iodine'
Iodine.threads = 1
Iodine.workers = 2
Process.fork { sleep(0.5); STDERR.puts("[#{Process.pid}] Master in fork? #{Iodine.master?}") }
Iodine.run_after(500) { STDERR.puts("[#{Process.pid}] Master? #{Iodine.master?}") }
Iodine.run_after(700) { Iodine.stop }
Iodine.start
```

Because `fork` was called from the master process, the process is still identifiers as a master process (allowing a second instance of iodine to run in parallel).

**Comment by boazsegev** [comment] 2019-06-28 11:22
P.S. 

Another possible workaround would be to set a custom `SIGINT` signal handler that does nothing. this could be used to replace the RSpec signal handler... although I think Opal's monkey-patch might prevent this behavior (I don't know how you would set a signal handler when the method was overridden).

Otherwise, avoiding cluster mode (using a single worker) will be your best bet for now.

**Comment by janbiedermann** [comment] 2019-06-28 11:58
Thanks @boazsegev , running with just threads makes things work. I am currently tracing a new crash:
https://travis-ci.org/isomorfeus/isomorfeus-framework/builds/551701272#L911

The Opal signal handling is not used here, that code is just for the browser or nodejs.

**Comment by janbiedermann** [comment] 2019-06-28 12:02
Whats the best way debugging iodine? What tools do you use?

**Comment by boazsegev** [comment] 2019-06-28 12:45
@janbiedermann ,

Thank you for exposing this issue! 🙏🏻

> hats the best way debugging iodine? What tools do you use?

I debug the C layer using the Clang debugger that comes with the macOS developer tools (`lldb`).

The C layer is written separately from the Ruby layer, so I usually have to write tests in C.

The hardest bugs to track down are those rooted in the C <=> Ruby bridge layer. Since Ruby doesn't allow me to debug inside the C functions I have to rely on core dumps and crash reports after finding a way to reproduce the issue reliably.

I see **the crash report** references the [`iodine_connection_fire_event` function](https://github.com/boazsegev/iodine/blob/a8670629dfb2e1f25cba21a0529d7d3e3dade3e4/ext/iodine/iodine_connection.c#L770-L835) and my first impression is that either:

1. (most probable, as `report_on_exception` is enabled and iodine's thread was probably terminated unexpectedly): an exception handler in Ruby killed the working threads, causing the code path to move outside of iodine's normal flow and breaking the internal state in a way that caused data corruption... or:

2. that a Ruby object passed to the callback might have been garbage collected before the callback was invoked.

I'll be thankful if you could send me an example application that would re-create the issue, so I could work on a fix.

In general, iodine should be able to catch unprotected exceptions exactly in order to avoid this issue. However, if the thread was explicitly killed, the best thing would be for iodine to crash, since the internal state would be compromised.

Kindly,
   Bo.

**Comment by janbiedermann** [comment] 2019-06-28 13:03
The most simple app for reproducing the crash is probably in the https://github.com/isomorfeus/isomorfeus-react repo, 
https://github.com/isomorfeus/isomorfeus-react/tree/master/ruby/test_app

Clone the repo, cd to ruby/test_app, yarn install, bundle install, bundle exec rspec -> crash.

**Comment by boazsegev** [comment] 2019-06-28 13:30
Hi @janbiedermann ,

Thank you for the test application.

I wonder - is there any way to re-create the issue in a simpler / more direct way?

The amount of moving parts in the test application is staggering. It includes gems that add code and multiple layers of abstraction as well as signal monitoring and monkey patches - any of which could be triggering the issue.

Consider, for example, if somewhere in the code some gem calls `Thread.current.exit`, maybe only in development mode... this will obviously cause the crash in the report and I won't be able to see the issue unless I dig through multiple layers of code.

To track the issue I need to find a way to reproduce the crash in a specific targeted manner, the narrower the better.

I'll start with the test_app, but if you have any ideas about how I could narrow down the issue to a specific function call / situation, that would be great.

Kindly,
   Bo.

**Comment by janbiedermann** [comment] 2019-06-28 13:57
You are right, lots of things going on. So far i was myself unable to narrow it down, still digging, i suspect, but i may be wrong, its some interaction with https://github.com/isomorfeus/isomorfeus-puppetmaster, https://github.com/isomorfeus/isomorfeus-puppetmaster/tree/master/ruby/lib/isomorfeus/puppetmaster

**Comment by boazsegev** [comment] 2019-06-28 14:23
FYI: couldn’t reproduce issue on Ruby 2.6... I’m hopping on a flight, so I’ll download 2.5 only later tonight.

**Comment by boazsegev** [comment] 2019-06-28 19:27
Hi @janbiedermann ,

I think I found the source of the issue.

For some reason, the exception raised wasn't inheriting Exception, which caused iodine's call to `#message` to raise a new (unprotected) exception, terminating the thread.

I pushed a patch but didn't release it yet. Feel free to test the master branch as see if it solves your issue.

Kindly,
   Bo.

**Comment by janbiedermann** [comment] 2019-06-29 05:48
Thanks @boazsegev , thats fixed, now i get a real error message at the end:
```
ERROR: Iodine caught an unprotected exception - NO MESSAGE / DATA AVAILABLE
INFO: (96545) detected exit signal.
INFO:    ---  Shutdown Complete  ---
```
Specs pass on Travis, so with Threads and only 1 worker i am happy for the moment. 👍

**Comment by boazsegev** [comment] 2019-06-29 08:06
FYI: The update should also work in cluster mode... Unless I missed a signal that could have been avoided...

**Comment by boazsegev** [comment] 2019-07-07 20:23
I released the update... none of my tests failed, but I still can't help feeling signal related issues are too complex to truly test properly. I guess I'll have to trust my manual tests and hope for the best.

Closing this issue.

**Closed by boazsegev** 2019-07-07 20:23 UTC
Labels: compatibility

**Comment by janbiedermann** [comment] 2019-07-09 05:20
Great! Thanks a lot @boazsegev!
