### ISSUE TITLE
Exception when using Fibers

### ISSUE THREAD

**Issue by adam12** [boazsegev/iodine#70] opened 2019-03-29 14:56 UTC
Hi Bo,

This should be an interesting one. I'm not _100%_ sure this lies in Iodine, but I can't reproduce it with any other server.

Here's the stacktrace:

```
Traceback (most recent call last):
        10: from example.rb:39:in `<main>'
         9: from /usr/home/adam/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
         8: from /usr/home/adam/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:297:in `start'
         7: from /usr/home/adam/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/iodine-0.7.27/lib/rack/handler/iodine.rb:13:in `run'
         6: from /usr/home/adam/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/iodine-0.7.27/lib/rack/handler/iodine.rb:13:in `start'
         5: from /usr/home/adam/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/roda-3.18.0/lib/roda/plugins/streaming.rb:85:in `each'
         4: from example.rb:32:in `block (3 levels) in <main>'
         3: from example.rb:32:in `copy_stream'
         2: from /usr/home/adam/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/down-4.6.1/lib/down/chunked_io.rb:162:in `readpartial'
         1: from /usr/home/adam/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/down-4.6.1/lib/down/chunked_io.rb:266:in `retrieve_chunk'
/usr/home/adam/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/down-4.6.1/lib/down/chunked_io.rb:266:in `resume': fiber called across stack rewinding barrier (FiberError)
```

And here's a reproduction script (also [available here](https://gist.github.com/339f18b304374cbe6b734bfb0522ba35)):

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "iodine", "0.7.27"
  gem "puma", "3.12.1"
  gem "down", "4.6.1"
  gem "roda"
end

module EachChunk
  def each_chunk(chunk_size = 1024)
    yield read(chunk_size) until eof?
  end
end

app = Class.new(Roda) do
  plugin :streaming

  route do |r|
    data = StringIO.new("This is the data")

    input = Down::ChunkedIO.new(
      size: data.size,
      chunks: data.extend(EachChunk).enum_for(:each_chunk),
      data: {
        content_type: "text/plain"
      }
    )

    stream do |output|
      IO.copy_stream(input, output)
    end
  end
end

server = ARGV[0] or abort "Usage: #{$0} iodine|puma"
Rack::Server.start(app: app, server: server.to_sym, :Port => 9292)
```

My uname
```
FreeBSD devmachine 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64
```

Moving the assignment of `input` into the `stream` block makes everything work, FYI, tho I don't believe that's a legit fix.

Cheers!

**Comment by boazsegev** [comment] 2019-03-29 22:12
@adam12 , thank you for opening this issue.

I'm not sure that this is an iodine issue, but it does expose a weakness in streaming logic handling - when an exception is raised within the `each` in the response `body`, iodine fails.

I added an exception protection layer for the `body.each` call, with hopes of making it a little more stable and easier to track down the error.

However, the error appears elusive. I get:

```text
ERROR: Iodine caught an unprotected exception - NoMethodError: undefined method `call' for nil:NilClass
/Users/2be/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/roda-3.18.0/lib/roda/plugins/streaming.rb:59:in `write'
config.ru:89:in `copy_stream'
config.ru:89:in `block (4 levels) in <main>'
/Users/2be/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/roda-3.18.0/lib/roda/plugins/streaming.rb:85:in `each'
/Users/2be/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/iodine-0.7.28/lib/rack/handler/iodine.rb:13:in `start'
```

This indicates the function `IO.copy_stream(input, output)` attempts to call `write` on a `nil` object. Compare with (where no error is reported):

```ruby
stream do |output|
  begin
    IO.copy_stream(input, output)    
  rescue Exception => e
  end
end
```

This appears (to me) to be an obscure error, since the original error, before I added protection around the `body`'s `each` block, was the `fiber called across stack rewinding barrier (FiberError)` error [seen here](https://github.com/ruby/ruby/blob/56557ec28a8712984a0e9744fd7547e797ec9b6b/cont.c#L1793).

Maybe I solved one issue in order to fall at the feet of a another?

---

**Side-Note**:

I highly recommend that streaming be avoided.

One reason is iodine specific, but part of the reason is true for all Rack servers (due to the Rack specification and the use of `each`):

- When "streaming" on a Rack server, using `each`, the application thread is busy within the thread loop.

    From any server's perspective, this is the same as collecting all the data before returning a valid response.

- Iodine, specifically, also tests some of the user headers for missing headers. One of these headers is the `Content-Length` header, which can only be tested after the `each` loop had completed and the body's length is finalized...

    So, in practice, the data isn't really streamed on iodine (though it is on Puma). 

I understand that this might raise a few questions, such as "how do you stream with iodine", or (perhaps more to the point) "how do you stream from behind Rack"?

The answer to this would be either WebSockets or SSE, both of which iodine supports.

Another option is the `Range` header which allows responses to send partial data to the client - this approach is often used when streaming movies or other media (i.e., quicktime).

Iodine's static file service supports the `Range` header requests for large static files, allowing browsers to stop and resume large downloads as well as to stream media.

There are other issues with streaming behind Rack as well, and [this blog post is also informative](http://blog.plataformatec.com.br/2012/06/why-your-web-framework-should-not-adopt-rack-api/).

**Comment by adam12** [comment] 2019-03-30 02:27
Thank you for the exceptionally detailed response, per usual!

> Maybe I solved one issue in order to fall at the feet of a another?

Indeed. With clarity has come more confusion :)

My original hypothesis was that the Fiber was being passed to another thread somehow and that's why this weird error had occurred, but with the new error, I'm out of ideas.

> I highly recommend that streaming be avoided.

Seems reasonable; this is a pet project that I've been exploring some new technology with.

> The answer to this would be either WebSockets or SSE, both of which iodine supports.

I'm using both WebSockets and SSE in other applications with Iodine (so thank you for Iodine! 💯) but sadly this wont' work in this scenario as it's a regular HTTP/1.1 request for an image.

I might just switch to using X-Sendfile, as I don't _really_ need to stream it in reality, I was just trying to prevent buffer bloat.

I did try your recent commits and they clarified the error but it still remains.  You can close this if you think there's no bug here; I'll happily defer to you on this one.

Thanks again!

**Comment by boazsegev** [comment] 2019-03-30 03:06
@adam12 ,

Thank you for keeping me updated.

> My original hypothesis was that the Fiber was being passed to another thread somehow and that's why this weird error had occurred, but with the new error, I'm out of ideas.

At the moment I'm at a loss as well.

I've tried a number of wild guesses, still thinking it might be a fiber related concern... but I suspect I might need to dig into the Roda plugin and try to find a way to reproduce the issue without the plugin (if I can).

I'll keep this open because:

1. The error occurs only on iodine. This is a strong indication that there is, somewhere, an issue which I just couldn't isolate. I want to give it more time.

2. I understand I can't avoid people attempting to stream data. I might want to re-think the question of how iodine handles this (which is why I added the feature request label). 

> I might just switch to using X-Sendfile, as I don't really need to stream it in reality, I was just trying to prevent buffer bloat.

If this is the reason, then please use X-Sendfile. Iodine can handle this task in a better way then a Ruby based streaming approach.

Iodine will automatically attempt to [send the file using the system's `sendfile`](https://github.com/boazsegev/iodine/blob/1753ae3daab699f6f6f8cf47e8b7ce9891e56452/ext/iodine/fio.c#L2683-L2731) (avoiding a user buffer). If this fails (i.e., [due to a TLS read/write hook](https://github.com/boazsegev/iodine/blob/1753ae3daab699f6f6f8cf47e8b7ce9891e56452/ext/iodine/fio.c#L2810-L2812)), iodine will [send the file a chunk at a time using a small temporary buffer](https://github.com/boazsegev/iodine/blob/1753ae3daab699f6f6f8cf47e8b7ce9891e56452/ext/iodine/fio.c#L2643-L2681).

**Note**: please notice that iodine's X-Sendfile support requires iodine's static file service. The assumption is that if iodine isn't handling static files, nginx / apache are (and they should be the ones handling the X-Sendfile header).

**Note 2**: when using other servers, (and specifically when using Puma, as can be seen [here](https://github.com/puma/puma/blob/0f8b10737e36fc24cdd572f76a739659b5fad9cb/lib/puma/server.rb#L785-L798) and [here](https://github.com/puma/puma/blob/0f8b10737e36fc24cdd572f76a739659b5fad9cb/lib/puma/server.rb#L985-L1003)) the streaming approach might block for IO (instead of buffering it) and expose the server to slow client attacks.

**Comment by adam12** [comment] 2019-03-30 03:06
> I added an exception protection layer for the `body.each` call, with hopes of making it a little more stable and easier to track down the error.

I'm not sure which commit broke, but somewhere after 237a428, returning a File object in a raw Rack response ends up returning a 0 length body.

Here's a repro (I used `bundler/inline` out of lazyness).

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "rack"

  if ENV["BROKEN"]
    gem "iodine", git: "https://github.com/boazsegev/iodine", ref: "1753ae3" # Latest commit & broken
  else
    gem "iodine", git: "https://github.com/boazsegev/iodine", ref: "237a428" # Working
  end
end

Rack::Server.start(server: :iodine, app: ->(env) {
  [200, {}, File.open(__FILE__)]
})
```

**Comment by boazsegev** [comment] 2019-03-30 03:26
Thanks, @adam12  🙏🏻🙏🏻🎉🎉🎉🎊

It probably was a fiber issue after all, and adding an exception protection layer somehow fixed it (maybe iodine was calling `each` from outside the GIL? I guess it must have).

Anyway, it seems I didn't update my code correctly and my previous commit had iodine calling `each` without a block...

Now it's all golden ☺️👍🏻

As an added bonus, the streaming plugin works (though my recommendation still stands).

**Comment by adam12** [comment] 2019-03-30 03:30
Tested the fix against both issues (streaming and `each`) and both work as expected.

Much thanks! I will be still heeding your advice about streaming.

**Comment by boazsegev** [comment] 2019-03-30 03:42
I moved the HTTP streaming feature discussion to the facil.io repo. Closing the issue.

Thanks again for opening this issue 🙏🏻👍🏻

**Closed by boazsegev** 2019-03-30 03:42 UTC
Labels: compatibility, feature request
